version: "3.9"
services:
  web:
    build: .
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
      - ./frontend/package.json:/frontend/package.json
      - ./frontend/package-lock.json:/frontend/package-lock.json
      - ./frontend/ThemeConfig.js:/frontend/ThemeConfig.js
    ports:
      - "3000:3000"
    command: npm run dev